### ISSUE TITLE
java.lang.NoSuchMethodError: com.intellij.lang.javascript.psi.JSParameterList.getParameters() Exception in Plugin - IntelliJ IDEA 2016.3.4

### ISSUE THREAD

**Issue by JanThiel** [CoreMedia/jangaroo-idea#11]
Getting tons of this exception while doing CM Studio Customizing in IDEA.
Using IDEA 2016.3.4 and Jangaroo 0.9 Plugin

```
While trying to inject AS3 into /workspace/modules/studio/blueprint-forms/src/main/joo/com/coremedia/blueprint/studio/forms/CMArticleForm.exml.: com.intellij.lang.javascript.psi.JSParameterList.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameter;
java.lang.NoSuchMethodError: com.intellij.lang.javascript.psi.JSParameterList.getParameters()[Lcom/intellij/lang/javascript/psi/JSParameter;
	at net.jangaroo.ide.idea.exml.ExmlLanguageInjector.injectAS(ExmlLanguageInjector.java:229)
	at net.jangaroo.ide.idea.exml.ExmlLanguageInjector.getLanguagesToInject(ExmlLanguageInjector.java:87)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl$PsiManagerRegisteredInjectorsAdapter.getLanguagesToInject(InjectedLanguageManagerImpl.java:491)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:458)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:313)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:145)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.findInside(InjectedLanguageUtil.java:410)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.tryOffset(InjectedLanguageUtil.java:389)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.findInjectedElementNoCommit(InjectedLanguageUtil.java:369)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.a(BraceHighlightingHandler.java:189)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.a(BraceHighlightingHandler.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1061)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.b(BraceHighlightingHandler.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fwienber** [comment]
See http://jangaroo.myjetbrains.com/youtrack/issue/IDEA-51
